### ISSUE TITLE
Unable to build--maturin failed, the module name must not contain a minus '-'

### ISSUE THREAD

**Issue by bwmcin** [insight-platform/Similari#102]
Following the instructions from https://medium.com/inside-in-sight/high-performance-python-sort-tracker-225c2b507562 resulted in a build failure, with the message maturin failed, the module name must not contain a minus '-' .  I edited the pyproject.toml file to change the project name back to similari (no -trackers-rs) and the build worked.

**Comment by bwsw** [comment]
Hello, @bwmcin. I need to check because, recently, CI was able to build everything with a new naming scheme which enabled uploading to PyPi.

**Comment by bwsw** [comment]
@bwmcin the problem is fixed.

**Comment by bwmcin** [comment]
I was able to successfully build Similari with the new updates.  Thank you for the quick response.

 

bwmcin
