### ISSUE TITLE
Geo crate needs to be updated

### ISSUE THREAD

**Issue by callanoc** [insight-platform/Similari#104]
Please update geo="^0.25.1" to avoid recursion limit overflow
https://github.com/rust-lang/rust/issues/110475#issuecomment-1646929665

**Comment by bwsw** [comment]
Hello, the version is updated in the current main. The new release will be published after CI passes.

**Comment by callanoc** [comment]
Thanks a lot!

**Comment by callanoc** [comment]
Do you know when you will have time to push the new version to crates.io 🙏 ? 
Thank you so much
