### ISSUE TITLE
EpochDB trait not public

### ISSUE THREAD

**Issue by rfechtner** [insight-platform/Similari#106]
Hi,

I would like to implement a custom Tracker using the [TrackerAPI](https://github.com/insight-platform/Similari/blob/58bcd5ee31baafa5d43fc6905035e6fa3366a4e6/src/trackers/tracker_api.rs#L9), whose signature is

```rust
pub trait TrackerAPI<TA, M, OA, E, N>
where
    TA: TrackAttributes<TA, OA>,
    M: ObservationMetric<TA, OA>,
    OA: ObservationAttributes,
    N: ChangeNotifier,
    E: EpochDb,
{ .. }
```

while the trait is public, the module containing the definition is not [trackers.rs](https://github.com/insight-platform/Similari/blob/58bcd5ee31baafa5d43fc6905035e6fa3366a4e6/src/trackers.rs#L6):

```rust
/// Trait that implements epoch db management
mod epoch_db;
```

Using the pre-implemented `SortAttributesOptions` is also not possible as the trait's functions are also private, ie. `epoch_db()` or `next_epoch()`, therefor I can't use them in my custom implementation without bringing `EpochDb` into scope.

Is the `EpochDB` mod deliberately private or I missing something in the API design? Or could we just:

```diff
- mod epoch_db;
+ pub mod epoch_db;
```

Cheers

**Comment by bwsw** [comment]
Hello. Sure, send a PR.

**Comment by bwsw** [comment]
I suppose you should take a look at the benches first. Because they are external to the crate and I never had limitations related to privacy.

**Comment by rfechtner** [comment]
Hi @bwsw, I have checked but non of the benchmarking examples use the `TrackerAPI` as they use the pre-implemented versions of Trackers. 

I will make some tests locally and craft a PR.

**Comment by bwsw** [comment]
@rfechtner yes, I will fix the CI/CD and craft a new release soon.
