### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by callanoc** [insight-platform/Similari#112]
Would it be possible to publish the latest version on crates.io? Thanks a lot!

**Comment by bwsw** [comment]
@callanoc I will.

**Comment by bwsw** [comment]
I need to address several clippy warnings before I can upload it. I'm sorry for the delay - will try finding time tomorrow.

**Comment by bwsw** [comment]
@callanoc hello. 
I published the package to crates under `0.26.11`. Sorry for the long awaiting.
