### ISSUE TITLE
2D Kalman Point Filter with missing data

### ISSUE THREAD

**Issue by awarebayes** [insight-platform/Similari#113]
Greetings, I would like use the class  Point2DKalmanFilter for tracking 2d points on a map, say car/plane movements. 
How do I properly handle missing data?

One approach would be to set the covariance matrix to a large number, following [1](https://stats.stackexchange.com/a/312050), [2](https://math.stackexchange.com/questions/982982/kalman-filter-with-missing-measurement-inputs/2350458#2350458).

I was unable to find a method to directly modify Point2DKalmanFilterState to accomplish that.

Is this the approach you rely on for missing data? I may open a PR with this functionality added, if needed.

**Comment by bwsw** [comment]
Hello,
you can propose your PR. Please implement tests too, to reflect your scenario.

**Comment by awarebayes** [comment]
I am not entirely sure on how to implement that, as I described.
I can do getters / setters for Point2DKalmanFilterState, maybe skipping update() is fine? Not really an expert on kalman filters....

[Kalman and Bayesian Filters in Python](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python) provides the following approach for missing data:

```
def update(self, Z, R=None):
"""
Add a new measurement (Z) to the kalman filter. If Z is None, nothing
is changed.
Optionally provide R to override the measurement noise for this
one call, otherwise self.R will be used.
self.residual, self.S, and self.K are stored in case you want to
inspect these variables. Strictly speaking they are not part of the
output of the Kalman filter, however, it is often useful to know
what these values are in various scenarios.
"""
  if Z is None:
      return
```

So maybe it's fine to just not call update, afterall

**Comment by bwsw** [comment]
@awarebayes Do not you consider just passing previous prediction results as current observations if there are no current observations?

**Comment by awarebayes** [comment]
Thanks for help, this solved my issue!
